'use strict';
let state,selectedManagedId=null,currentCustomSound=null,previewAudio=null,editingTaskId=null,editingReminderId=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dayKey=()=>new Date().toLocaleDateString('sv-SE');
function occurs(t){const d=new Date(),k=dayKey();return t.kind==='daily'||(t.kind==='once'&&t.date===k)||(t.kind==='weekly'&&t.weekdays?.includes(d.getDay()));}
function completed(id){return state.completions.some(x=>x.taskId===id&&x.date===dayKey());}
function deviceName(id){const n=state.networkStatus;if(!id||id===n.deviceId)return n.deviceName||'自己';const all=Object.values(n.peers||{});return all.find(x=>x.deviceId===id)?.name||id;}
function weekdayLabel(days=[]){const normalized=[...new Set(days.map(Number).filter(x=>Number.isInteger(x)&&x>=0&&x<=6))].sort((a,b)=>a-b),key=normalized.join(',');if(key==='1,2,3,4,5')return'平日';if(key==='0,6')return'假日';const names=['日','一','二','三','四','五','六'];return normalized.length?`每週${normalized.map(x=>`週${names[x]}`).join('、')}`:'未指定星期';}
function repeatLabel(x){return x.repeat==='daily'||x.kind==='daily'?'每天':x.repeat==='once'||x.kind==='once'?x.date:weekdayLabel(x.weekdays);}
function reminderSchedule(r){if(r.triggerMode==='afterStart')return `${r.relativeRepeat?'每隔':'開始使用後'} ${Number(r.delayMinutes)||0} 分鐘`;return `${r.time||''} · ${repeatLabel(r)}`;}
function soundName(r){return r.sound==='custom'?(r.customSoundName||'自訂音效'):({chime:'清脆鈴聲',water:'水滴聲',soft:'柔和提示',alarm:'關機警示'}[r.sound]||r.sound);}
function weekdayMode(days=[]){const key=[...days].sort().join(',');return key==='1,2,3,4,5'?'weekday':key==='0,6'?'weekend':'custom';}
function selectedWeekdays(modeId,inputId){const mode=$(modeId).value;return mode==='weekday'?[1,2,3,4,5]:mode==='weekend'?[0,6]:$(inputId).value.split(',').map(Number).filter(x=>Number.isInteger(x)&&x>=0&&x<=6);}
function toggleWeekdayInput(modeId,inputId){$(inputId).hidden=$(modeId).value!=='custom';}
function upgradeWeekdayField(inputId,modeId){const input=$(inputId),label=input.closest('label');label.innerHTML=`每週日期<select id="${modeId.slice(1)}"><option value="weekday">平日（週一至週五）</option><option value="weekend">假日（週六、週日）</option><option value="custom">自訂星期</option></select><input id="${inputId.slice(1)}" placeholder="0 日～6 六，例如 1,3,5">`;$(modeId).onchange=()=>toggleWeekdayInput(modeId,inputId);toggleWeekdayInput(modeId,inputId);}
function playTone(kind){const ctx=new AudioContext(),patterns={chime:[[660,.16],[880,.28]],water:[[900,.08],[620,.18]],soft:[[440,.25],[550,.35]],alarm:[[740,.2],[520,.2],[740,.35]]},seq=patterns[kind]||patterns.chime;let at=ctx.currentTime;for(const [freq,len] of seq){const o=ctx.createOscillator(),g=ctx.createGain();o.type=kind==='alarm'?'square':'sine';o.frequency.value=freq;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.18,at+.02);g.gain.exponentialRampToValueAtTime(.0001,at+len);o.connect(g).connect(ctx.destination);o.start(at);o.stop(at+len);at+=len+.06;}}
function itemTask(t,canComplete=true){return `<div class="item task ${completed(t.id)?'done':''}"><div class="row spread"><b>${esc(t.title)}</b><span class="pill">${t.rewardMinutes?`+${t.rewardMinutes} 分鐘`:'無時間獎勵'}</span></div><p class="muted">${esc(repeatLabel(t))} · ${esc(deviceName(t.targetDeviceId))}</p><div class="row">${canComplete&&!completed(t.id)?`<button class="primary complete" data-id="${t.id}">完成打勾</button>`:''}${!t.remote?`<button class="edit-task" data-id="${t.id}">編輯</button><button class="delete-task" data-id="${t.id}">刪除</button>`:''}</div></div>`;}
async function render(){state=await window.rhythm.getState();const today=state.tasks.filter(x=>(!x.targetDeviceId||x.targetDeviceId===state.networkStatus.deviceId)&&occurs(x));const done=today.filter(x=>completed(x.id));const used=Math.floor((state.usage[`me:${dayKey()}`]||0)/60),usage=state.rewardUsage?.[dayKey()]||{};const reward=state.completions.filter(x=>x.date===dayKey()&&!x.remote).reduce((a,x)=>a+(x.rewardMinutes||0),0);const quota=Math.max(0,state.settings.dailyLimitMinutes+(Number(usage.quotaMinutes)||0)-used);let clock=null;if(['clock','both'].includes(state.settings.timeMode)){const [h,m]=state.settings.shutdownTime.split(':').map(Number),end=new Date(),extension=state.settings.rewardExtendsClock?Math.min(Number(usage.clockMinutes)||0,Number(state.settings.maxRewardClockExtensionMinutes)||0):0;end.setHours(h,m+extension,0,0);clock=Math.max(0,Math.ceil((end-Date.now())/60000));}const remaining=state.settings.timeMode==='clock'?clock:state.settings.timeMode==='both'?Math.min(quota,clock):quota;
 $('#summary-time').textContent=state.settings.timeControlEnabled?`${remaining} 分鐘`:'未啟用';$('#summary-used').textContent=state.settings.timeControlEnabled?`已使用 ${used} 分鐘`:'提醒與責任表仍會正常運作';$('#summary-tasks').textContent=`${done.length} / ${today.length}`;$('#summary-reward').textContent=`今日獲得 +${reward} · 時間晶幣 ${Number(state.rewardBalanceMinutes)||0} 分鐘`;$('#today-tasks').innerHTML=today.length?today.map(x=>itemTask(x,true)).join(''):'<div class="empty">今天沒有安排責任</div>';$('#task-list').innerHTML=state.tasks.length?state.tasks.map(x=>itemTask(x,false)).join(''):'<div class="empty">還沒有任務</div>';
 $('#reminder-list').innerHTML=state.reminders.length?state.reminders.map(r=>`<div class="item" style="--item-color:${r.color}"><div class="row spread"><b>${esc(r.title)}</b><span class="pill">${r.type==='shutdown'?'關機':r.type==='task'?'任務':'中間'}提醒</span></div><p>${esc(reminderSchedule(r))} · ${esc(deviceName(r.targetDeviceId))}</p><div class="muted">音效：${esc(soundName(r))}</div>${!r.remote?`<div class="row"><button class="edit-rem" data-id="${r.id}">編輯</button><button class="delete-rem" data-id="${r.id}">刪除</button></div>`:''}</div>`).join(''):'<div class="empty">還沒有提醒</div>';
 $('#set-start-windows').checked=Boolean(state.settings.startWithWindows);$('#set-time-enabled').checked=state.settings.timeControlEnabled!==false;$('#set-earliest-enabled').checked=Boolean(state.settings.earliestStartEnabled);$('#set-earliest-time').value=state.settings.earliestStartTime||'07:00';$('#set-time-mode').value=state.settings.timeMode||'quota';$('#set-shutdown-time').value=state.settings.shutdownTime||'21:30';$('#set-extend-clock').checked=state.settings.rewardExtendsClock!==false;$('#set-max-clock-reward').value=state.settings.maxRewardClockExtensionMinutes??30;$('#set-limit').value=state.settings.dailyLimitMinutes;$('#set-cap').value=state.settings.rewardCapMinutes;$('#set-grace').value=state.settings.shutdownGraceMinutes;$('#set-simulate').checked=state.settings.simulateShutdown;const shouldHide=!state.runtime.shutdownAt;if($('#cancel-card').hidden!==shouldHide)$('#cancel-card').hidden=shouldHide;renderFamily();renderTargets();renderHelp();toggleTimeFields();bindDynamic();renderParentLock();}
function devices(){const n=state.networkStatus,list=[{deviceId:n.deviceId,name:`${n.deviceName}（這台）`,online:true,role:n.memberRole}];for(const p of Object.values(n.peers||{}))if(p.deviceId!==n.deviceId)list.push(p);return list;}
function renderTargets(){const html=devices().map(x=>`<option value="${esc(x.deviceId)}">${esc(x.name)}${x.online===false?'（離線）':''}</option>`).join('');for(const id of ['#task-target','#rem-target']){const old=$(id).value;$(id).innerHTML=html;if(old&&[...$(id).options].some(x=>x.value===old))$(id).value=old;}}
function renderFamily(){
 const n=state.networkStatus,connected=n.role!=='local';$('#family-local').hidden=connected;$('#family-connected').hidden=!connected;if(!connected){$('#peer-list').innerHTML='';$('#managed-area').hidden=true;return;}
 const roleText=n.role==='host'?'主要管理者':n.memberRole==='co-manager'?'共同管理者':'家庭成員';$('#family-name').textContent=n.familyName;$('#family-role').textContent=`${roleText}：${n.deviceName}`;$('#family-online').textContent=n.online?'已連線':'離線';$('#family-online').className=`pill ${n.online?'online':'offline'}`;
 $('#host-info').innerHTML=n.role==='host'?`<p>主要電腦 IP：<b>${esc(n.addresses.join(' 或 '))}</b></p><p>連接埠：${n.port}</p><div class="muted">六位配對碼（10 分鐘有效）</div><div class="code">${esc(n.pairingCode)}</div><p class="muted">${n.pairingExpiresAt?`有效至 ${new Date(n.pairingExpiresAt).toLocaleTimeString('zh-TW')}`:'已過期'}</p><button id="refresh-pairing">產生新配對碼</button>`:`<p>主要電腦：<b>${esc(n.hostIp)}</b></p><p class="muted">${n.lastSync?`上次同步 ${new Date(n.lastSync).toLocaleTimeString('zh-TW')}`:'等待第一次同步'}${n.pendingManagerActions?` · ${n.pendingManagerActions} 項管理操作等待傳送`:''}</p>`;
 $('#managed-consent').hidden=n.role!=='client'||n.memberRole==='co-manager';$('#allow-management').checked=Boolean(n.managementEnabled);
 $('#peer-list').innerHTML=devices().map(x=>{const role=x.role==='primary-manager'?'主要管理者':x.role==='co-manager'?'共同管理者':'家庭成員';const roleButton=n.role==='host'&&x.deviceId!==n.deviceId&&!x.managementEnabled?`<button class="peer-role" data-id="${x.deviceId}" data-role="${x.role==='co-manager'?'member':'co-manager'}">${x.role==='co-manager'?'撤銷共同管理者':'設為共同管理者'}</button>`:'';return`<div class="item"><div class="row spread"><b>${esc(x.name)}</b><span class="pill">${role}</span></div><div class="${x.online===false?'offline':'online'}">${x.online===false?'離線':'在線'}${x.managementEnabled?' · 受管理裝置':''}</div>${roleButton}</div>`;}).join('');
 document.querySelectorAll('.peer-role').forEach(b=>b.onclick=async()=>{const label=b.dataset.role==='co-manager'?'授予共同管理權限':'撤銷共同管理權限';if(confirm(`確定${label}？`)){await window.rhythm.setPeerRole(b.dataset.id,b.dataset.role);await render();}});if($('#refresh-pairing'))$('#refresh-pairing').onclick=async()=>{await window.rhythm.refreshPairingCode();render();};renderManagedArea(n);
}
function renderManagedArea(n){const list=state.managedDevices||[],canManage=n.role==='host'||n.memberRole==='co-manager';$('#managed-area').hidden=!canManage;if(!canManage)return;$('#managed-device-list').innerHTML=list.length?list.map(x=>`<button class="item managed-open" data-id="${x.deviceId}" style="text-align:left"><b>${esc(x.name)}</b><div class="${x.online?'online':'offline'}">${x.online?'在線':'離線'} · ${x.reminders.length} 個提醒 · ${x.tasks.length} 項責任</div></button>`).join(''):'<div class="empty">尚無裝置授權家庭管理者管理</div>';document.querySelectorAll('.managed-open').forEach(b=>b.onclick=()=>{selectedManagedId=b.dataset.id;renderManagedEditor();});renderAudit();if(selectedManagedId)renderManagedEditor();}
function renderAudit(){let box=$('#management-audit');if(!box){box=document.createElement('div');box.id='management-audit';box.className='card';$('#managed-area').append(box);}const names={"settings-updated":'修改時間設定',"reminder-toggled":'切換提醒',"usage-reset":'重置今日使用時間',"manager-granted":'授予共同管理者',"manager-revoked":'撤銷共同管理者'};const logs=state.managementAudit||[];box.innerHTML=`<h2>最近管理紀錄</h2>${logs.length?logs.slice(0,12).map(x=>`<div class="row spread"><span>${esc(x.actorName)} · ${names[x.type]||x.type}</span><span class="muted">${new Date(x.at).toLocaleString('zh-TW')}</span></div>`).join(''):'<div class="muted">尚無管理操作</div>'}`;}
function renderManagedEditor(){
 const d=(state.managedDevices||[]).find(x=>x.deviceId===selectedManagedId);if(!d){$('#managed-editor').hidden=true;return;}
 $('#managed-editor').hidden=false;$('#managed-title').textContent=`管理 ${d.name}`;$('#managed-sync-state').textContent=d.resetPending?'重置時間：等待孩子電腦套用':d.online?'線上，最多約 5 秒套用':'離線，等待下次連線';$('#managed-sync-state').className=`pill ${d.resetPending||!d.online?'offline':'online'}`;
 $('#remote-enabled').checked=d.settings.timeControlEnabled!==false;$('#remote-earliest-enabled').checked=Boolean(d.settings.earliestStartEnabled);$('#remote-earliest-time').value=d.settings.earliestStartTime||'07:00';$('#remote-mode').value=d.settings.timeMode||'quota';$('#remote-limit').value=d.settings.dailyLimitMinutes??120;$('#remote-time').value=d.settings.shutdownTime||'21:30';$('#remote-cap').value=d.settings.rewardCapMinutes??60;$('#remote-grace').value=d.settings.shutdownGraceMinutes??10;$('#remote-extend').checked=d.settings.rewardExtendsClock!==false;$('#remote-max-clock-reward').value=d.settings.maxRewardClockExtensionMinutes??30;
 let reset=$('#remote-reset-usage');if(!reset){reset=document.createElement('button');reset.id='remote-reset-usage';reset.className='danger';$('#remote-save').closest('.form').after(reset);}reset.textContent=d.resetPending?'等待套用重置命令…':'重置今日使用時間';reset.disabled=d.resetPending;reset.onclick=async()=>{if(confirm(`確定將 ${d.name} 今天已使用的時間歸零？\n任務獎勵和完成紀錄會保留。`)){await window.rhythm.resetManagedUsage(d.deviceId);await render();}};
 $('#remote-reminders').innerHTML=d.reminders.length?d.reminders.map(r=>`<div class="item" style="--item-color:${r.color||'#8174ee'}"><div class="row spread"><b>${esc(r.title)}</b><label class="row"><input class="check remote-rem-toggle" data-id="${r.id}" type="checkbox" ${r.enabled?'checked':''}>啟用</label></div><div class="muted">${esc(reminderSchedule(r))} · ${r.type==='shutdown'?'關機提醒':'一般提醒'}</div></div>`).join(''):'<div class="empty">沒有提醒</div>';
 $('#remote-tasks').innerHTML=d.tasks.length?d.tasks.map(t=>`<div class="item"><b>${esc(t.title)}</b><div class="muted">${esc(repeatLabel(t))}${t.rewardMinutes?` · +${t.rewardMinutes} 分鐘`:''}</div></div>`).join(''):'<div class="empty">沒有責任項目</div>';document.querySelectorAll('.remote-rem-toggle').forEach(x=>x.onchange=async()=>{await window.rhythm.toggleManagedReminder(selectedManagedId,x.dataset.id,x.checked);await render();});
}
function beginTaskEdit(id){const t=state.tasks.find(x=>x.id===id&&!x.remote);if(!t)return;editingTaskId=id;$('#task-form').hidden=false;$('#task-form h2').textContent='編輯責任';$('#task-save').textContent='儲存修改';$('#task-title').value=t.title||'';$('#task-target').value=t.targetDeviceId||state.networkStatus.deviceId;$('#task-kind').value=t.kind||'daily';$('#task-date').value=t.date||'';$('#task-weekday-mode').value=weekdayMode(t.weekdays);$('#task-weekdays').value=(t.weekdays||[]).join(',');toggleWeekdayInput('#task-weekday-mode','#task-weekdays');$('#task-reward').value=Number(t.rewardMinutes)||0;$('#task-form').scrollIntoView({behavior:'smooth',block:'center'});}
async function beginReminderEdit(id){const r=state.reminders.find(x=>x.id===id&&!x.remote);if(!r)return;editingReminderId=id;$('#reminder-form').hidden=false;$('#reminder-form h2').textContent='編輯提醒';$('#rem-save').textContent='儲存修改';$('#rem-title').value=r.title||'';$('#rem-target').value=r.targetDeviceId||state.networkStatus.deviceId;$('#rem-trigger').value=r.triggerMode||'clock';$('#rem-time').value=r.time||'';$('#rem-delay').value=Number(r.delayMinutes)||20;$('#rem-relative-repeat').checked=Boolean(r.relativeRepeat);$('#rem-type').value=r.type||'gentle';$('#rem-repeat').value=r.repeat||'daily';$('#rem-date').value=r.date||'';$('#rem-weekday-mode').value=weekdayMode(r.weekdays);$('#rem-weekdays').value=(r.weekdays||[]).join(',');toggleWeekdayInput('#rem-weekday-mode','#rem-weekdays');$('#rem-color').value=r.color||'#7c6df2';if(r.sound==='custom'&&r.customSoundId){currentCustomSound={id:r.customSoundId,name:r.customSoundName||'自訂音效'};if(!$('#rem-sound option[value="custom"]'))$('#rem-sound').add(new Option('自訂音效','custom'));$('#rem-sound-file').textContent=`已選擇：${currentCustomSound.name}`;}else{currentCustomSound=null;$('#rem-sound-file').textContent='可使用 MP3、WAV、OGG、M4A（最多 5 MB）';}$('#rem-sound').value=r.sound||'chime';toggleReminderTiming();$('#reminder-form').scrollIntoView({behavior:'smooth',block:'center'});}
function bindDynamic(){document.querySelectorAll('.complete').forEach(b=>b.onclick=async()=>{await window.rhythm.completeTask(b.dataset.id);render();});document.querySelectorAll('.edit-task').forEach(b=>b.onclick=()=>beginTaskEdit(b.dataset.id));document.querySelectorAll('.edit-rem').forEach(b=>b.onclick=()=>beginReminderEdit(b.dataset.id));document.querySelectorAll('.delete-task').forEach(b=>b.onclick=async()=>{if(confirm('確定刪除這項責任？')){await window.rhythm.deleteTask(b.dataset.id);if(editingTaskId===b.dataset.id)resetTaskForm();render();}});document.querySelectorAll('.delete-rem').forEach(b=>b.onclick=async()=>{if(confirm('確定刪除這個提醒？')){await window.rhythm.deleteReminder(b.dataset.id);if(editingReminderId===b.dataset.id)resetReminderForm();render();}});}
function versionParts(v){return String(v||'0').replace(/^v/i,'').split('.').map(x=>parseInt(x,10)||0);}
function newerVersion(a,b){const aa=versionParts(a),bb=versionParts(b);for(let i=0;i<Math.max(aa.length,bb.length);i++){if((aa[i]||0)!==(bb[i]||0))return(aa[i]||0)>(bb[i]||0);}return false;}
function renderHelp(){$('#help-auto').checked=state.settings.autoCheckUpdates!==false;$('#help-version').textContent=`v${state.appVersion}`;const peers=Object.values(state.networkStatus.peers||{}),newer=peers.filter(x=>x.appVersion&&x.appVersion!=='未知'&&newerVersion(x.appVersion,state.appVersion));$('#help-family-versions').innerHTML=peers.length?peers.map(x=>`<div class="row spread"><span>${esc(x.name)}</span><span class="pill">v${esc(x.appVersion||'未知')}</span></div>`).join(''):'<div class="muted">尚未連接家庭裝置</div>';const u=state.runtime.updateStatus;if(newer.length)$('#help-status').textContent=`家庭中有較新版本：v${newer.sort((a,b)=>newerVersion(a.appVersion,b.appVersion)?-1:1)[0].appVersion}`;else if(!u)$('#help-status').textContent='尚未檢查官方 GitHub Release';else if(u.error)$('#help-status').textContent=`檢查失敗：${u.error}`;else if(u.available)$('#help-status').textContent=`發現新版 v${u.latestVersion}`;else $('#help-status').textContent=`目前已是最新版（v${state.appVersion}）`;$('#help-open').hidden=!u?.available||!u?.url;}
function renderParentLock(){const lock=state.parentLock||{configured:false,unlocked:true};$('#parent-lock-card').hidden=!lock.configured;$('#parent-unlock-row').hidden=lock.unlocked;$('#parent-lock-now').hidden=!lock.unlocked;$('#parent-lock-state').textContent=lock.unlocked?'家長控制已解鎖（5 分鐘）':'管理功能已鎖定';const selectors=['#add-task','#add-reminder','#task-save','#rem-save','#settings-save','#create-family','#join-family','#leave-family','#allow-management','#remote-save','#help-save','#help-check','#refresh-pairing','.edit-task','.delete-task','.edit-rem','.delete-rem','.peer-role','#remote-reset-usage'];document.querySelectorAll(selectors.join(',')).forEach(x=>{x.disabled=lock.configured&&!lock.unlocked;x.title=x.disabled?'請先輸入家長密碼解鎖':'';});}
upgradeWeekdayField('#task-weekdays','#task-weekday-mode');upgradeWeekdayField('#rem-weekdays','#rem-weekday-mode');
$('#set-time-mode').closest('label').insertAdjacentHTML('beforebegin','<label class="full row"><input class="check" id="set-earliest-enabled" type="checkbox">限制每天最早開始使用時間</label><label>最早開始時間<input id="set-earliest-time" type="time" value="07:00"></label>');
$('#extend-field').insertAdjacentHTML('afterend','<label id="max-clock-reward-field">關機時間最多可用晶幣延長（分鐘）<input id="set-max-clock-reward" type="number" min="0" value="30"></label>');
$('#remote-mode').closest('label').insertAdjacentHTML('beforebegin','<label class="full row"><input class="check" id="remote-earliest-enabled" type="checkbox">限制這台裝置最早開始使用時間</label><label>最早開始時間<input id="remote-earliest-time" type="time" value="07:00"></label>');
$('#remote-extend').insertAdjacentHTML('afterend','<label>關機時間最多可用晶幣延長（分鐘）<input id="remote-max-clock-reward" type="number" min="0" value="30"></label>');
$('#set-cap').closest('label').hidden=true;$('#remote-cap').closest('label').hidden=true;
document.querySelector('.nav').insertAdjacentHTML('beforeend','<button data-page="help">HELP／關於</button>');document.querySelector('.content').insertAdjacentHTML('beforeend','<section id="help" class="page"><h1>HELP／關於家庭節奏</h1><div class="grid"><div class="card"><div class="muted">目前版本</div><div id="help-version" class="summary">--</div><p class="muted">家庭裝置同步時會自動交換版本號。</p></div><div class="card"><h2>官方更新檢查</h2><p>更新來源：<b>github.com/DLAfvr/family-rhythm</b></p><label class="row"><input class="check" id="help-auto" type="checkbox">啟動時自動檢查更新</label><div class="row"><button id="help-save">儲存更新設定</button><button id="help-check" class="primary">立即檢查更新</button><button id="help-open" hidden>開啟下載頁</button></div><p id="help-status" class="muted"></p></div></div><div class="card"><h2>家庭裝置版本</h2><div id="help-family-versions"></div></div><div class="card"><h2>使用說明</h2><p>家庭節奏會在家中內網同步提醒、責任表與管理設定。若 GitHub 暫時無法連線，不會影響既有功能。</p><p class="muted">更新來源固定為官方倉庫；只會開啟正式 Release 下載頁，不會在未確認時自行安裝。</p></div></section>');
document.querySelector('.side').insertAdjacentHTML('beforeend','<div id="parent-lock-card" class="lock-card" hidden><b id="parent-lock-state">管理功能已鎖定</b><div id="parent-unlock-row"><input id="parent-unlock-password" type="password" placeholder="家長密碼"><button id="parent-unlock" class="primary">解鎖</button><div id="parent-unlock-error" class="offline"></div></div><button id="parent-lock-now" hidden>立即鎖定</button></div>');
document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-page],.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.page}`).classList.add('active');});
$('#help-save').onclick=async()=>{await window.rhythm.saveUpdateSettings({autoCheckUpdates:$('#help-auto').checked});alert('更新設定已儲存');render();};$('#help-check').onclick=async()=>{$('#help-status').textContent='正在向官方 GitHub 倉庫檢查…';await window.rhythm.saveUpdateSettings({autoCheckUpdates:$('#help-auto').checked});await window.rhythm.checkUpdate();render();};$('#help-open').onclick=()=>window.rhythm.openUpdatePage();
$('#parent-unlock').onclick=async()=>{const out=await window.rhythm.unlockParent($('#parent-unlock-password').value);if(!out.ok){$('#parent-unlock-error').textContent=out.reason;return;}$('#parent-unlock-password').value='';$('#parent-unlock-error').textContent='';render();};$('#parent-unlock-password').onkeydown=e=>{if(e.key==='Enter')$('#parent-unlock').click();};$('#parent-lock-now').onclick=async()=>{await window.rhythm.lockParent();render();};
function resetTaskForm(){editingTaskId=null;$('#task-form h2').textContent='任務內容';$('#task-save').textContent='儲存任務';$('#task-title').value='';$('#task-kind').value='daily';$('#task-date').value='';$('#task-weekday-mode').value='weekday';$('#task-weekdays').value='';toggleWeekdayInput('#task-weekday-mode','#task-weekdays');$('#task-reward').value=0;}
function resetReminderForm(){editingReminderId=null;currentCustomSound=null;$('#reminder-form h2').textContent='提醒內容';$('#rem-save').textContent='儲存提醒';$('#rem-title').value='';$('#rem-trigger').value='clock';$('#rem-time').value='';$('#rem-delay').value=20;$('#rem-relative-repeat').checked=false;$('#rem-type').value='gentle';$('#rem-repeat').value='daily';$('#rem-date').value='';$('#rem-weekday-mode').value='weekday';$('#rem-weekdays').value='';toggleWeekdayInput('#rem-weekday-mode','#rem-weekdays');$('#rem-color').value='#7c6df2';$('#rem-sound').value='chime';$('#rem-sound-file').textContent='可使用 MP3、WAV、OGG、M4A（最多 5 MB）';toggleReminderTiming();}
$('#add-task').onclick=()=>{if(editingTaskId)resetTaskForm();$('#task-form').hidden=!$('#task-form').hidden;};$('#add-reminder').onclick=()=>{if(editingReminderId)resetReminderForm();$('#reminder-form').hidden=!$('#reminder-form').hidden;toggleReminderTiming();};
$('#task-save').onclick=async()=>{const title=$('#task-title').value.trim();if(!title)return;await window.rhythm.saveTask({id:editingTaskId||undefined,title,targetDeviceId:$('#task-target').value,kind:$('#task-kind').value,date:$('#task-date').value,weekdays:selectedWeekdays('#task-weekday-mode','#task-weekdays'),rewardMinutes:Number($('#task-reward').value)||0});$('#task-form').hidden=true;resetTaskForm();render();};
function toggleReminderTiming(){const relative=$('#rem-trigger').value==='afterStart';$('#rem-clock-fields').hidden=relative;$('#rem-relative-fields').hidden=!relative;}
$('#rem-trigger').onchange=toggleReminderTiming;
$('#rem-sound-preview').onclick=async()=>{const kind=$('#rem-sound').value;if(kind!=='custom')return playTone(kind);if(!currentCustomSound)return alert('請先選擇自己的音效');const asset=await window.rhythm.getSoundAsset(currentCustomSound.id);if(!asset)return alert('找不到這個音效，請重新選擇');previewAudio?.pause();previewAudio=new Audio(asset.dataUrl);previewAudio.play().catch(()=>alert('這個音效無法播放，請換一個檔案'));};
$('#rem-sound-custom').onclick=async()=>{try{const asset=await window.rhythm.chooseCustomSound();if(!asset)return;currentCustomSound=asset;if(!$('#rem-sound option[value="custom"]'))$('#rem-sound').add(new Option('自訂音效','custom'));$('#rem-sound').value='custom';$('#rem-sound-file').textContent=`已選擇：${asset.name}（${(asset.size/1024/1024).toFixed(2)} MB）`;}catch(e){alert(e.message||'無法加入音效');}};
$('#rem-sound').onchange=()=>{if($('#rem-sound').value!=='custom')$('#rem-sound-file').textContent='可使用 MP3、WAV、OGG、M4A（最多 5 MB）';};
$('#rem-save').onclick=async()=>{const title=$('#rem-title').value.trim(),triggerMode=$('#rem-trigger').value,time=$('#rem-time').value,delayMinutes=Number($('#rem-delay').value),sound=$('#rem-sound').value;if(!title||(triggerMode==='clock'&&!time)||(triggerMode==='afterStart'&&delayMinutes<1))return alert('請填寫提醒名稱和有效時間');if(sound==='custom'&&!currentCustomSound)return alert('請先選擇自己的音效');await window.rhythm.saveReminder({id:editingReminderId||undefined,title,triggerMode,time,delayMinutes,relativeRepeat:$('#rem-relative-repeat').checked,targetDeviceId:$('#rem-target').value,type:$('#rem-type').value,repeat:$('#rem-repeat').value,date:$('#rem-date').value,weekdays:selectedWeekdays('#rem-weekday-mode','#rem-weekdays'),color:$('#rem-color').value,sound,customSoundId:sound==='custom'?currentCustomSound.id:null,customSoundName:sound==='custom'?currentCustomSound.name:null,memberId:'me'});$('#reminder-form').hidden=true;resetReminderForm();render();};
function toggleTimeFields(){const enabled=$('#set-time-enabled').checked,mode=$('#set-time-mode').value,clock=mode!=='quota',quota=mode!=='clock';$('#time-control-fields').style.display=enabled?'grid':'none';$('#clock-field').style.display=clock?'block':'none';$('#extend-field').style.display=clock?'flex':'none';$('#max-clock-reward-field').style.display=clock?'block':'none';$('#limit-field').style.display=quota?'block':'none';}
$('#set-time-mode').onchange=toggleTimeFields;
$('#set-time-enabled').onchange=toggleTimeFields;
$('#settings-save').onclick=async()=>{await window.rhythm.saveSettings({startWithWindows:$('#set-start-windows').checked,timeControlEnabled:$('#set-time-enabled').checked,earliestStartEnabled:$('#set-earliest-enabled').checked,earliestStartTime:$('#set-earliest-time').value,timeMode:$('#set-time-mode').value,shutdownTime:$('#set-shutdown-time').value,rewardExtendsClock:$('#set-extend-clock').checked,maxRewardClockExtensionMinutes:Number($('#set-max-clock-reward').value),dailyLimitMinutes:Number($('#set-limit').value),rewardCapMinutes:Number($('#set-cap').value),shutdownGraceMinutes:Number($('#set-grace').value),password:$('#set-password').value,simulateShutdown:$('#set-simulate').checked});$('#set-password').value='';alert('設定已儲存');render();};
$('#cancel-shutdown').onclick=async()=>{const ok=await window.rhythm.cancelShutdown($('#cancel-password').value);alert(ok?'已取消關機':'家長密碼不正確');render();};
$('#create-family').onclick=async()=>{try{$('#family-error').textContent='';await window.rhythm.createFamily({familyName:$('#create-family-name').value.trim(),deviceName:$('#create-device-name').value.trim()});render();}catch(e){$('#family-error').textContent=`建立失敗：${e.message}`;}};
$('#join-family').onclick=async()=>{try{$('#family-error').textContent='正在連線…';await window.rhythm.joinFamily({hostIp:$('#join-host').value.trim(),code:$('#join-code').value.trim(),deviceName:$('#join-device-name').value.trim()});$('#family-error').textContent='';render();}catch(e){$('#family-error').textContent=`加入失敗：${e.message}`;}};
$('#sync-family').onclick=async()=>{try{await window.rhythm.syncFamily();render();}catch(e){$('#family-error').textContent=`同步失敗：${e.message}`;}};
$('#allow-management').onchange=async()=>{try{await window.rhythm.setManaged($('#allow-management').checked);render();}catch(e){$('#family-error').textContent=`設定失敗：${e.message}`;}};
$('#remote-save').onclick=async()=>{if(!selectedManagedId)return;await window.rhythm.updateManagedSettings(selectedManagedId,{timeControlEnabled:$('#remote-enabled').checked,earliestStartEnabled:$('#remote-earliest-enabled').checked,earliestStartTime:$('#remote-earliest-time').value,timeMode:$('#remote-mode').value,dailyLimitMinutes:Number($('#remote-limit').value),shutdownTime:$('#remote-time').value,rewardCapMinutes:Number($('#remote-cap').value),shutdownGraceMinutes:Number($('#remote-grace').value),rewardExtendsClock:$('#remote-extend').checked,maxRewardClockExtensionMinutes:Number($('#remote-max-clock-reward').value)});alert('已儲存；孩子電腦在線時約 5 秒內套用。');await render();};
$('#leave-family').onclick=async()=>{if(confirm('確定離開這個家庭？本機提醒和任務會保留。')){await window.rhythm.leaveFamily();render();}};
window.rhythm.onStateChanged(()=>{if(!['INPUT','SELECT'].includes(document.activeElement?.tagName))render();});setInterval(()=>{if(state?.parentLock?.expiresAt&&Date.now()>state.parentLock.expiresAt)render();},5000);render();
