'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('pointerdown',event=>{const field=event.target.closest?.('input,select,textarea');if(!field||field.disabled)return;const recover=()=>{if(document.activeElement!==field)field.focus({preventScroll:true});};if(!document.hasFocus())window.rhythm.focusCurrentWindow().finally(()=>requestAnimationFrame(recover));else requestAnimationFrame(recover);},true);
window.addEventListener('focus',()=>{const field=document.activeElement;if(field?.matches?.('input,select,textarea')&&!field.disabled)requestAnimationFrame(()=>field.focus({preventScroll:true}));});
const deviceId=new URLSearchParams(location.search).get('id');
let state,device,vacations=[],vacationEdit=-1,editingTaskId=null,editingReminderId=null,currentCustomSound=null,settingsLoaded=false,settingsDirty=false;
const dayKey=()=>new Date().toLocaleDateString('sv-SE');
const uid=()=>crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function weekdaysFor(mode,text=''){if(mode==='weekday')return[1,2,3,4,5];if(mode==='weekend')return[0,6];return[...new Set(text.split(/[,，\s]+/).map(Number).filter(n=>n>=0&&n<=6))].sort();}
function weekdayMode(days=[]){const v=[...days].sort().join(',');return v==='1,2,3,4,5'?'weekday':v==='0,6'?'weekend':'custom';}
function repeatLabel(x){if(x.kind==='bounty')return`懸賞 · ${Number(x.maxCompletions)||1} 人`;if(x.kind==='daily'||x.repeat==='daily')return'每天';if(x.kind==='once'||x.repeat==='once')return x.date||'單次';const names=['日','一','二','三','四','五','六'],mode=weekdayMode(x.weekdays);return mode==='weekday'?'平日':mode==='weekend'?'假日':`每週 ${(x.weekdays||[]).map(n=>`週${names[n]}`).join('、')}`;}
function statsHtml(stats){if(!stats)return'<div class="empty">這天尚無同步統計</div>';const row=(x,mark)=>`<div class="stats-row"><b>${mark} ${esc(x.title)}</b><span class="muted">${x.completedAt?` · ${new Date(x.completedAt).toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit'})}`:''}${x.rewardMinutes?` · +${x.rewardMinutes} 分鐘`:''}</span></div>`;const rows=[...stats.completed.map(x=>row(x,'✓')),...stats.pending.map(x=>row(x,'○ 待完成')),...stats.missed.map(x=>row(x,'× 未完成'))];return`<div class="stats-list">${rows.join('')||'<div class="empty">這天沒有責任</div>'}</div><p class="muted">共獲得 ${stats.earnedMinutes||0} 分鐘時間晶幣</p>`;}
function setDirty(value=true){settingsDirty=Boolean(value);$('#save-bar').hidden=!settingsDirty;$('#save-all').textContent=settingsDirty?'儲存設定 · 尚未儲存':'儲存設定';}
function setSettings(s){$('#enabled').checked=s.timeControlEnabled!==false;$('#mode').value=s.timeMode||'quota';$('#limit').value=s.dailyLimitMinutes??120;$('#shutdown').value=s.shutdownTime||'21:30';$('#earliest-enabled').checked=Boolean(s.earliestStartEnabled);$('#earliest').value=s.earliestStartTime||'07:00';$('#day-type-enabled').checked=Boolean(s.dayTypeScheduleEnabled);$('#weekday-limit').value=s.weekdayDailyLimitMinutes??s.dailyLimitMinutes??120;$('#weekend-limit').value=s.weekendDailyLimitMinutes??s.dailyLimitMinutes??120;$('#weekday-time').value=s.weekdayShutdownTime||s.shutdownTime||'21:30';$('#weekend-time').value=s.weekendShutdownTime||s.shutdownTime||'21:30';$('#grace').value=s.shutdownGraceMinutes??10;$('#reward-cap').value=s.rewardCapMinutes??60;$('#extend-clock').checked=s.rewardExtendsClock!==false;$('#extension').value=s.maxRewardClockExtensionMinutes??30;vacations=(s.vacationSchedules||[]).map(x=>({...x}));renderVacations();settingsLoaded=true;syncUsageDependencies();setDirty(false);}
function renderVacations(){const list=$('#vacation-list');list.innerHTML=vacations.length?vacations.map((x,i)=>`<div class="item vacation-row"><div><b>${esc(x.name||'假期')}</b><div class="muted">${x.annual?'每年 ':''}${esc(x.annual?x.startMonthDay:x.startDate)} ～ ${esc(x.annual?x.endMonthDay:x.endDate)} · 每日 ${Number(x.dailyLimitMinutes)||0} 分鐘 · ${esc(x.shutdownTime)} 關機</div></div><div class="actions"><button data-vac-edit="${i}">編輯</button><button class="danger" data-vac-delete="${i}">刪除</button></div></div>`).join(''):'<div class="empty">尚未設定寒暑假或其他假期區間</div>';document.querySelectorAll('[data-vac-edit]').forEach(b=>b.onclick=()=>editVacation(Number(b.dataset.vacEdit)));document.querySelectorAll('[data-vac-delete]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.vacDelete);if(confirm(`確定刪除「${vacations[i]?.name||'假期'}」？`)){vacations.splice(i,1);cancelVacation();renderVacations();setDirty();}});}
function toggleAnnual(){const annual=$('#vac-annual').checked;for(const id of ['#vac-start','#vac-end']){const el=$(id);el.type=annual?'text':'date';el.placeholder=annual?'MM-DD，例如 07-01':'';}}
function cancelVacation(){vacationEdit=-1;for(const id of ['#vac-name','#vac-start','#vac-end','#vac-limit','#vac-time'])$(id).value='';$('#vac-annual').checked=false;toggleAnnual();$('#vac-save').textContent='加入假期區間';$('#vac-cancel').hidden=true;}
function editVacation(i){const x=vacations[i];if(!x)return;vacationEdit=i;$('#vac-name').value=x.name||'';$('#vac-annual').checked=Boolean(x.annual);toggleAnnual();$('#vac-start').value=x.annual?x.startMonthDay:x.startDate||'';$('#vac-end').value=x.annual?x.endMonthDay:x.endDate||'';$('#vac-limit').value=x.dailyLimitMinutes??0;$('#vac-time').value=x.shutdownTime||'';$('#vac-save').textContent='儲存假期修改';$('#vac-cancel').hidden=false;}
function saveVacation(){const annual=$('#vac-annual').checked,start=$('#vac-start').value.trim(),end=$('#vac-end').value.trim(),name=$('#vac-name').value.trim(),dailyLimitMinutes=Number($('#vac-limit').value),shutdownTime=$('#vac-time').value;const valid=annual?/^(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/.test(start)&&/^(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$/.test(end):Boolean(start&&end&&start<=end);if(!name||!valid||!Number.isFinite(dailyLimitMinutes)||dailyLimitMinutes<0||!shutdownTime)return alert('請填寫假期名稱、正確日期區間、每日額度與關機時間');const old=vacationEdit>=0?vacations[vacationEdit]:null,item={id:old?.id||uid(),name,annual,dailyLimitMinutes,shutdownTime,...(annual?{startMonthDay:start,endMonthDay:end}:{startDate:start,endDate:end})};if(vacationEdit>=0)vacations[vacationEdit]=item;else vacations.push(item);cancelVacation();renderVacations();setDirty();}
function renderTasks(){const tasks=(device.tasks||[]).filter(x=>!x.deletedAt);$('#tasks').innerHTML=tasks.length?tasks.map(x=>`<div class="item"><div class="row spread"><div><b>${esc(x.title)}</b><div class="muted">${esc(repeatLabel(x))}${x.rewardMinutes?` · +${x.rewardMinutes} 分鐘`:''}${x.enabled===false?' · 已關閉':''}</div></div><div class="actions"><label class="row"><input class="check" data-task-toggle="${x.id}" type="checkbox" ${x.enabled!==false?'checked':''}>啟用</label><button data-task-edit="${x.id}">編輯</button><button data-task-copy="${x.id}">複製內容</button><button class="danger" data-task-delete="${x.id}">刪除</button></div></div></div>`).join(''):'<div class="empty">沒有責任項目</div>';document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>beginTaskEdit(b.dataset.taskEdit));document.querySelectorAll('[data-task-copy]').forEach(b=>b.onclick=()=>copyFormItem('task',device.tasks.find(x=>x.id===b.dataset.taskCopy)));document.querySelectorAll('[data-task-delete]').forEach(b=>b.onclick=()=>deleteItem('tasks',b.dataset.taskDelete));document.querySelectorAll('[data-task-toggle]').forEach(b=>b.onchange=()=>toggleItem('tasks',b.dataset.taskToggle,b.checked));}
function resetTask(){editingTaskId=null;$('#task-editor-title').textContent='新增責任';$('#task-title').value='';$('#task-kind').value='once';$('#task-enabled').checked=true;$('#task-date').value=dayKey();$('#task-weekday-mode').value='weekday';$('#task-weekdays').value='';$('#task-reward').value=0;$('#task-max').value=1;$('#task-reset-custom').checked=false;$('#task-reset').value='00:00';toggleTaskFields();}
function toggleTaskFields(){const kind=$('#task-kind').value,customReset=$('#task-reset-custom').checked;$('#task-date-label').hidden=kind!=='once';$('#task-weekday-label').hidden=kind!=='weekly';$('#task-weekdays-label').hidden=kind!=='weekly'||$('#task-weekday-mode').value!=='custom';$('#task-max-label').hidden=kind!=='bounty';$('#task-reset-label').hidden=false;$('#task-reset').disabled=!customReset;$('#task-reset-label').classList.toggle('conditional-off',!customReset);}
function beginTaskEdit(id){const t=device.tasks.find(x=>x.id===id);if(!t)return;editingTaskId=id;$('#task-editor').hidden=false;$('#task-editor-title').textContent='編輯責任';$('#task-title').value=t.title||'';$('#task-kind').value=t.kind||'once';$('#task-enabled').checked=t.enabled!==false;$('#task-date').value=t.date||dayKey();$('#task-weekday-mode').value=weekdayMode(t.weekdays);$('#task-weekdays').value=(t.weekdays||[]).join(',');$('#task-reward').value=Number(t.rewardMinutes)||0;$('#task-max').value=Number(t.maxCompletions)||1;$('#task-reset-custom').checked=Boolean(t.customReset);$('#task-reset').value=t.resetTime||'00:00';toggleTaskFields();$('#task-editor').scrollIntoView({behavior:'smooth',block:'center'});}
async function saveTask(){const title=$('#task-title').value.trim(),kind=$('#task-kind').value;if(!title)return alert('請輸入責任內容');if(kind==='once'&&!$('#task-date').value)return alert('請選擇單次責任日期');const old=device.tasks.find(x=>x.id===editingTaskId)||{};const item={...old,id:editingTaskId||uid(),title,kind,enabled:$('#task-enabled').checked,date:kind==='once'?$('#task-date').value:'',weekdays:kind==='weekly'?weekdaysFor($('#task-weekday-mode').value,$('#task-weekdays').value):[],rewardMinutes:Number($('#task-reward').value)||0,maxCompletions:Number($('#task-max').value)||1,customReset:$('#task-reset-custom').checked,resetTime:$('#task-reset').value||'00:00',memberId:'me'};await window.rhythm.updateManagedItem(deviceId,'tasks',item,false);$('#task-editor').hidden=true;resetTask();await render(false);}
function copyFormItem(kind,item){if(!item)return;const clean={...item};for(const key of ['id','targetDeviceId','creatorDeviceId','updatedAt','deletedAt','remote','round'])delete clean[key];localStorage.setItem('family-rhythm-form-clipboard',JSON.stringify({kind,item:clean,copiedAt:new Date().toISOString()}));alert(kind==='task'?'已複製責任內容，可貼到任何責任編輯器。':'已複製提醒內容，可貼到任何提醒編輯器。');}
function readFormClipboard(expected){let clip;try{clip=JSON.parse(localStorage.getItem('family-rhythm-form-clipboard')||'null');}catch{}if(!clip)return alert('目前沒有可貼上的內容');if(clip.kind!==expected)return alert(expected==='task'?'剪貼簿裡是提醒，不能貼到責任。':'剪貼簿裡是責任，不能貼到提醒。');return clip.item;}
function pasteTask(){const t=readFormClipboard('task');if(!t)return;resetTask();$('#task-editor').hidden=false;$('#task-editor-title').textContent='貼上為新責任';$('#task-title').value=t.title||'';$('#task-kind').value=t.kind||'once';$('#task-enabled').checked=t.enabled!==false;$('#task-date').value=t.date||dayKey();$('#task-weekday-mode').value=weekdayMode(t.weekdays);$('#task-weekdays').value=(t.weekdays||[]).join(',');$('#task-reward').value=Number(t.rewardMinutes)||0;$('#task-max').value=Number(t.maxCompletions)||1;$('#task-reset-custom').checked=Boolean(t.customReset);$('#task-reset').value=t.resetTime||'00:00';toggleTaskFields();$('#task-editor').scrollIntoView({behavior:'smooth',block:'center'});}
function renderReminders(){const reminders=(device.reminders||[]).filter(x=>!x.deletedAt);$('#reminders').innerHTML=reminders.length?reminders.map(x=>`<div class="item"><div class="row spread"><div><b>${esc(x.title)}</b><div class="muted">${x.triggerMode==='afterStart'?`開始使用後 ${Number(x.delayMinutes)||0} 分鐘`:esc(x.time||'未設定')} · ${esc(repeatLabel(x))}${x.enabled===false?' · 已關閉':''}</div></div><div class="actions"><label class="row"><input class="check" data-rem-toggle="${x.id}" type="checkbox" ${x.enabled!==false?'checked':''}>啟用</label><button data-rem-edit="${x.id}">編輯</button><button data-rem-copy="${x.id}">複製內容</button><button class="danger" data-rem-delete="${x.id}">刪除</button></div></div></div>`).join(''):'<div class="empty">沒有提醒</div>';document.querySelectorAll('[data-rem-edit]').forEach(b=>b.onclick=()=>beginReminderEdit(b.dataset.remEdit));document.querySelectorAll('[data-rem-copy]').forEach(b=>b.onclick=()=>copyFormItem('reminder',device.reminders.find(x=>x.id===b.dataset.remCopy)));document.querySelectorAll('[data-rem-delete]').forEach(b=>b.onclick=()=>deleteItem('reminders',b.dataset.remDelete));document.querySelectorAll('[data-rem-toggle]').forEach(b=>b.onchange=()=>toggleItem('reminders',b.dataset.remToggle,b.checked));}
function resetReminder(){editingReminderId=null;currentCustomSound=null;$('#reminder-editor-title').textContent='新增提醒';$('#rem-title').value='';$('#rem-trigger').value='clock';$('#rem-enabled').checked=true;$('#rem-time').value='';$('#rem-repeat').value='daily';$('#rem-date').value=dayKey();$('#rem-weekday-mode').value='weekday';$('#rem-weekdays').value='';$('#rem-delay').value=20;$('#rem-relative-repeat').checked=false;$('#rem-type').value='gentle';$('#rem-color').value='#7c6df2';$('#rem-sound').value='chime';$('#rem-sound-file').textContent='可使用 MP3、WAV、OGG、M4A（最多 5 MB）';toggleReminderFields();}
function toggleReminderFields(){const relative=$('#rem-trigger').value==='afterStart',repeat=$('#rem-repeat').value;$('#rem-clock').hidden=relative;$('#rem-relative').hidden=!relative;$('#rem-date-label').hidden=repeat!=='once';$('#rem-weekday-label').hidden=repeat!=='weekly';$('#rem-weekdays-label').hidden=repeat!=='weekly'||$('#rem-weekday-mode').value!=='custom';}
function beginReminderEdit(id){const r=device.reminders.find(x=>x.id===id);if(!r)return;editingReminderId=id;$('#reminder-editor').hidden=false;$('#reminder-editor-title').textContent='編輯提醒';$('#rem-title').value=r.title||'';$('#rem-trigger').value=r.triggerMode||'clock';$('#rem-enabled').checked=r.enabled!==false;$('#rem-time').value=r.time||'';$('#rem-repeat').value=r.repeat||'daily';$('#rem-date').value=r.date||dayKey();$('#rem-weekday-mode').value=weekdayMode(r.weekdays);$('#rem-weekdays').value=(r.weekdays||[]).join(',');$('#rem-delay').value=Number(r.delayMinutes)||20;$('#rem-relative-repeat').checked=Boolean(r.relativeRepeat);$('#rem-type').value=r.type||'gentle';$('#rem-color').value=r.color||'#7c6df2';if(r.sound==='custom'&&r.customSoundId){currentCustomSound={id:r.customSoundId,name:r.customSoundName||'自訂音效'};if(!$('#rem-sound option[value="custom"]'))$('#rem-sound').add(new Option('自訂音效','custom'));$('#rem-sound-file').textContent=`已選擇：${currentCustomSound.name}`;}else currentCustomSound=null;$('#rem-sound').value=r.sound||'chime';toggleReminderFields();$('#reminder-editor').scrollIntoView({behavior:'smooth',block:'center'});}
function pasteReminder(){const r=readFormClipboard('reminder');if(!r)return;resetReminder();$('#reminder-editor').hidden=false;$('#reminder-editor-title').textContent='貼上為新提醒';$('#rem-title').value=r.title||'';$('#rem-trigger').value=r.triggerMode||'clock';$('#rem-enabled').checked=r.enabled!==false;$('#rem-time').value=r.time||'';$('#rem-repeat').value=r.repeat||'daily';$('#rem-date').value=r.date||dayKey();$('#rem-weekday-mode').value=weekdayMode(r.weekdays);$('#rem-weekdays').value=(r.weekdays||[]).join(',');$('#rem-delay').value=Number(r.delayMinutes)||20;$('#rem-relative-repeat').checked=Boolean(r.relativeRepeat);$('#rem-type').value=r.type||'gentle';$('#rem-color').value=r.color||'#7c6df2';if(r.sound==='custom'&&r.customSoundId){currentCustomSound={id:r.customSoundId,name:r.customSoundName||'自訂音效'};if(!$('#rem-sound option[value="custom"]'))$('#rem-sound').add(new Option('自訂音效','custom'));$('#rem-sound-file').textContent=`已選擇：${currentCustomSound.name}`;}$('#rem-sound').value=r.sound||'chime';toggleReminderFields();$('#reminder-editor').scrollIntoView({behavior:'smooth',block:'center'});}
async function saveReminder(){const title=$('#rem-title').value.trim(),triggerMode=$('#rem-trigger').value,time=$('#rem-time').value,delayMinutes=Number($('#rem-delay').value),sound=$('#rem-sound').value,repeat=$('#rem-repeat').value;if(!title||(triggerMode==='clock'&&!time)||(triggerMode==='afterStart'&&delayMinutes<1))return alert('請填寫提醒名稱和有效時間');if(triggerMode==='clock'&&repeat==='once'&&!$('#rem-date').value)return alert('請選擇單次提醒日期');if(sound==='custom'&&!currentCustomSound)return alert('請先選擇自己的音效');const old=device.reminders.find(x=>x.id===editingReminderId)||{};const item={...old,id:editingReminderId||uid(),title,enabled:$('#rem-enabled').checked,triggerMode,time,delayMinutes,relativeRepeat:$('#rem-relative-repeat').checked,type:$('#rem-type').value,repeat,date:repeat==='once'?$('#rem-date').value:'',weekdays:repeat==='weekly'?weekdaysFor($('#rem-weekday-mode').value,$('#rem-weekdays').value):[],color:$('#rem-color').value,sound,customSoundId:sound==='custom'?currentCustomSound.id:null,customSoundName:sound==='custom'?currentCustomSound.name:null,memberId:'me'};await window.rhythm.updateManagedItem(deviceId,'reminders',item,false);$('#reminder-editor').hidden=true;resetReminder();await render(false);}
async function deleteItem(kind,id){const item=device[kind].find(x=>x.id===id);if(!item||!confirm(`確定刪除「${item.title}」？`))return;await window.rhythm.updateManagedItem(deviceId,kind,item,true);await render(false);}
async function toggleItem(kind,id,enabled){const item=device[kind].find(x=>x.id===id);if(!item)return;await window.rhythm.updateManagedItem(deviceId,kind,{...item,enabled},false);await render(false);}
async function render(force=false){state=await window.rhythm.getState();device=(state.managedDevices||[]).find(x=>x.deviceId===deviceId);if(!device){$('#title').textContent='無法管理這台裝置';$('#sync').textContent='裝置尚未授權，或已離開家庭。';document.querySelectorAll('details,.card,#save-all').forEach(x=>x.hidden=true);return;}$('#title').textContent=`管理 ${device.name}`;$('#sync').textContent=`${device.online?'在線':'離線快取'} · ${device.receivedAt?`資料更新 ${new Date(device.receivedAt).toLocaleString('zh-TW')}`:'尚未同步'}`;$('#sync').className=device.online?'online':'offline';$('#remaining').textContent=device.remainingMinutes==null?'--':`${device.remainingMinutes} 分鐘`;$('#balance').textContent=`${device.rewardBalanceMinutes||0} 分鐘`;$('#date').max=dayKey();if(!$('#date').value)$('#date').value=dayKey();$('#stats').innerHTML=statsHtml((device.stats||[]).find(x=>x.date===$('#date').value));$('#reset').disabled=Boolean(device.resetPending);$('#reset').textContent=device.resetPending?'等待重置套用':'重置今日使用時間';if(!settingsLoaded||force)setSettings(device.settings||{});renderTasks();renderReminders();$('#lock-state').textContent=device.parentLockConfigured?'這台裝置已設定家長鎖。':'這台裝置目前沒有家長鎖。';$('#request-lock').disabled=device.parentLockConfigured||device.lockRequestPending;$('#request-lock').textContent=device.lockRequestPending?'等待裝置設定家長鎖':device.parentLockConfigured?'家長鎖已設定':'要求恢復家長鎖';}
function syncUsageDependencies(){const enabled=$('#enabled').checked,mode=$('#mode').value,split=$('#day-type-enabled').checked,clock=mode!=='quota',quota=mode!=='clock',earliest=enabled&&$('#earliest-enabled').checked,extend=enabled&&clock&&$('#extend-clock').checked;$('#earliest').disabled=!earliest;$('#earliest').closest('label').classList.toggle('conditional-off',!earliest);$('#limit').disabled=!enabled||!quota||split;$('#shutdown').disabled=!enabled||!clock||split;$('#day-type-fields').hidden=false;for(const id of ['#weekday-limit','#weekend-limit'])$(id).disabled=!enabled||!split||!quota;for(const id of ['#weekday-time','#weekend-time'])$(id).disabled=!enabled||!split||!clock;$('#day-type-fields').classList.toggle('conditional-off',!enabled||!split);$('#extension').disabled=!extend;$('#extension').closest('label').classList.toggle('conditional-off',!extend);for(const id of ['#mode','#grace','#reward-cap','#earliest-enabled','#day-type-enabled','#extend-clock'])$(id).disabled=!enabled;}
async function saveSettings(){await window.rhythm.updateManagedSettings(deviceId,{timeControlEnabled:$('#enabled').checked,timeMode:$('#mode').value,dailyLimitMinutes:Number($('#limit').value),shutdownTime:$('#shutdown').value,earliestStartEnabled:$('#earliest-enabled').checked,earliestStartTime:$('#earliest').value,dayTypeScheduleEnabled:$('#day-type-enabled').checked,weekdayDailyLimitMinutes:Number($('#weekday-limit').value),weekendDailyLimitMinutes:Number($('#weekend-limit').value),weekdayShutdownTime:$('#weekday-time').value,weekendShutdownTime:$('#weekend-time').value,vacationSchedules:vacations,shutdownGraceMinutes:Number($('#grace').value),rewardCapMinutes:Number($('#reward-cap').value),rewardExtendsClock:$('#extend-clock').checked,maxRewardClockExtensionMinutes:Number($('#extension').value)});settingsLoaded=false;setDirty(false);alert('設定已儲存；裝置在線時約 5 秒內套用。');await render(true);}
$('#save-all').onclick=()=>saveSettings().catch(e=>alert(e.message));$('#date').onchange=()=>{$('#stats').innerHTML=statsHtml((device.stats||[]).find(x=>x.date===$('#date').value));};$('#reset').onclick=async()=>{if(confirm(`確定重置 ${device.name} 今天的使用時間？`)){await window.rhythm.resetManagedUsage(deviceId);render(true);}};
for(const id of ['#enabled','#mode','#earliest-enabled','#day-type-enabled','#extend-clock'])$(id).onchange=syncUsageDependencies;$('#vac-annual').onchange=toggleAnnual;$('#vac-save').onclick=saveVacation;$('#vac-cancel').onclick=cancelVacation;
for(const id of ['#enabled','#mode','#limit','#shutdown','#earliest-enabled','#earliest','#day-type-enabled','#weekday-limit','#weekend-limit','#weekday-time','#weekend-time','#grace','#reward-cap','#extend-clock','#extension']){const el=$(id);el.addEventListener('input',()=>setDirty());el.addEventListener('change',()=>setDirty());}
$('#save-changes').onclick=()=>saveSettings().catch(e=>alert(e.message));
$('#discard-settings').onclick=()=>{setSettings(device.settings||{});cancelVacation();};
$('#task-add').onclick=()=>{resetTask();$('#task-editor').hidden=false;};$('#task-paste').onclick=pasteTask;$('#task-cancel').onclick=()=>{$('#task-editor').hidden=true;resetTask();};$('#task-kind').onchange=toggleTaskFields;$('#task-weekday-mode').onchange=toggleTaskFields;$('#task-reset-custom').onchange=toggleTaskFields;$('#task-save').onclick=()=>saveTask().catch(e=>alert(e.message));
$('#reminder-add').onclick=()=>{resetReminder();$('#reminder-editor').hidden=false;};$('#reminder-paste').onclick=pasteReminder;$('#rem-cancel').onclick=()=>{$('#reminder-editor').hidden=true;resetReminder();};$('#rem-trigger').onchange=toggleReminderFields;$('#rem-repeat').onchange=toggleReminderFields;$('#rem-weekday-mode').onchange=toggleReminderFields;$('#rem-save').onclick=()=>saveReminder().catch(e=>alert(e.message));
$('#rem-custom').onclick=async()=>{try{const asset=await window.rhythm.chooseCustomSound();if(!asset)return;currentCustomSound=asset;if(!$('#rem-sound option[value="custom"]'))$('#rem-sound').add(new Option('自訂音效','custom'));$('#rem-sound').value='custom';$('#rem-sound-file').textContent=`已選擇：${asset.name}（${(asset.size/1024/1024).toFixed(2)} MB）`;}catch(e){alert(e.message||'無法加入音效');}};
$('#rem-preview').onclick=async()=>{const type=$('#rem-sound').value;if(type==='custom'){if(!currentCustomSound)return alert('請先選擇自己的音效');const data=await window.rhythm.getSoundAsset(currentCustomSound.id);if(!data)return alert('找不到音效檔案');new Audio(data).play();return;}const ctx=new AudioContext(),o=ctx.createOscillator(),g=ctx.createGain(),freq={chime:880,water:620,soft:440,alarm:1040}[type]||660;o.frequency.value=freq;g.gain.setValueAtTime(.14,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.65);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.7);};
$('#request-lock').onclick=async()=>{if(!confirm(`要求 ${device.name} 恢復家長鎖？\n基於安全考量，新密碼必須在該裝置本機設定，不會透過內網傳送。`))return;try{$('#lock-feedback').textContent='正在送出要求…';await window.rhythm.requestManagedParentLock(deviceId);$('#lock-feedback').textContent=device.online?'已送出；等待對方在本機設定新密碼。':'裝置目前離線；要求已排程，會在下次連線時送達。';await render(true);}catch(e){$('#lock-feedback').textContent='';alert(e.message||'無法送出家長鎖要求');}};
window.rhythm.onStateChanged(()=>{const tag=document.activeElement?.tagName;if(!['INPUT','SELECT','TEXTAREA'].includes(tag))render(false);});
render();
