'use strict';
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('rhythm', {
  getState: () => ipcRenderer.invoke('get-state'),
  unlockParent: password => ipcRenderer.invoke('parent-unlock', password),
  lockParent: () => ipcRenderer.invoke('parent-lock'),
  openDashboard: () => ipcRenderer.invoke('open-dashboard'),
  closeWindow: () => ipcRenderer.invoke('close-window'),
  saveReminder: v => ipcRenderer.invoke('save-reminder', v),
  deleteReminder: id => ipcRenderer.invoke('delete-reminder', id),
  saveTask: v => ipcRenderer.invoke('save-task', v),
  deleteTask: id => ipcRenderer.invoke('delete-task', id),
  completeTask: id => ipcRenderer.invoke('complete-task', id),
  saveSettings: v => ipcRenderer.invoke('save-settings', v),
  acknowledgeReminder: id => ipcRenderer.invoke('ack-reminder', id),
  cancelShutdown: password => ipcRenderer.invoke('cancel-shutdown', password),
  respondReward: value => ipcRenderer.invoke('respond-reward', value),
  saveUpdateSettings: value => ipcRenderer.invoke('save-update-settings', value),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  openUpdatePage: () => ipcRenderer.invoke('open-update-page'),
  exitApp: password => ipcRenderer.invoke('exit-app', password),
  createFamily: value => ipcRenderer.invoke('network-create', value),
  joinFamily: value => ipcRenderer.invoke('network-join', value),
  leaveFamily: () => ipcRenderer.invoke('network-leave'),
  syncFamily: () => ipcRenderer.invoke('network-sync'),
  setManaged: enabled => ipcRenderer.invoke('network-set-managed', enabled),
  refreshPairingCode: () => ipcRenderer.invoke('network-refresh-pairing'),
  updateManagedSettings: (deviceId, patch) => ipcRenderer.invoke('managed-settings-update', deviceId, patch),
  toggleManagedReminder: (deviceId, reminderId, enabled) => ipcRenderer.invoke('managed-reminder-toggle', deviceId, reminderId, enabled),
  resetManagedUsage: deviceId => ipcRenderer.invoke('managed-usage-reset', deviceId),
  setPeerRole: (deviceId, role) => ipcRenderer.invoke('network-set-peer-role', deviceId, role),
  chooseCustomSound: () => ipcRenderer.invoke('choose-custom-sound'),
  getSoundAsset: assetId => ipcRenderer.invoke('get-sound-asset', assetId),
  onStateChanged: fn => ipcRenderer.on('state-changed', fn)
});
